from self_Dialogs.Fisher_score_D import *
from self_Dialogs.TTest_D import *
from self_Dialogs.elastic_network_D import *
from self_Dialogs.linear_D import *
from self_Dialogs.rbf_D import *
from self_Dialogs.rf_D import *
from self_Dialogs.knn_D import *
from self_Dialogs.TTest_D import *
from self_Dialogs.plot_D import *
from self_Dialogs.k_describle import *
from self_Dialogs.Lasso_D import *
from self_Dialogs.cnn_D import *